### ISSUE TITLE
Bug: Unable to play any media from card

### ISSUE THREAD

**Issue by spicerackk** [JurajNyiri/PlexMeetsHomeAssistant#29]
**Describe the bug**
[1610457704] Plex media not found using payload: '{"title":"Harold & Kumar Escape from Guantanamo Bay"}'

**To Reproduce**
1. Click on any title 

**Expected behavior**
The movie to begin playback, or the option to select playback device.

**Screenshots**
N/A

**Checks**
Please check below if true:

[x] I am running Home Assistant on HTTP protocol
[ ] I am running BOTH Home Assistant AND Plex on HTTPS protocol
[x] My Plex server is accessible through protocol, port and ip/hostname I have specified for the card.

**Version**
2.0.12

**Additional context**
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 479, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 519, in play_media
    media, _ = lookup_plex_media(self.hass, media_type, media_id)
  File "/usr/src/homeassistant/homeassistant/components/plex/services.py", line 122, in lookup_plex_media
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Plex media not found using payload: '{"title":"Harold & Kumar Escape from Guantanamo Bay"}'

**Comment by spicerackk** [comment]
restarted HA and it worked. no idea what happened.
